### PR TITLE
Implement jitter reduction

### PR DESCRIPTION
**Pull request by mklss**
This implements jitter reduction as in #38.

I've used this a few times, and it seems to work. However, there is some unexpected behaviour.
Sometimes, the finger detection seems to fail with `PositionStabilityThreshold = 0`. In fact, the changes seem to negatively affect performance and leads to a bit of sluggishness. Very brief fast touches are ignored. However, I observe very same behaviour when I compile without the changes. So maybe it's the locally compiled executable which is the problem. Are optimizations required (and how would I enable them).

### CODE REVIEW

**Comment by mklss** [comment]
@StollD: Do you have time to review/test (and merge) this? If you won't merge, do you know why running iptsd from terminal (even without the changes) the movement is more jerky/it feels like the update frequency is lower. Also, just replacing /usr/bin/iptsd with the build breaks ("Display size is 0!".), so I suppose something special happens for these builds.

**Comment by StollD** [comment]
Sorry I've been really busy the last weeks so this got pushed further and further behind. :/
From a glance over it the code looks good, so I will just merge it before letting you wait another month.

> If you won't merge, do you know why running iptsd from terminal (even without the changes) the movement is more jerky/it feels like the update frequency is lower.

Did you build with optimizations (`meson build -Doptimization=2? meson doesnt enable them by default, while our packages do.

> Also, just replacing /usr/bin/iptsd with the build breaks ("Display size is 0!".),

Local builds will have their prefix set to `/usr/local`. This means that the directory for the config files evaluates to `/usr/local/share/ipts`. The release packages set the prefix to `/usr`, so the path is `/usr/share/ipts`. If you run it directly from the checked out repo it will work, because the program falls back to loading the configs from `./config`.

Either install your local build with `sudo ninja -C build install`, or build with `meson build --prefix=/usr`

**Comment by tmarkov** [comment]
@StollD @mklss The lack of absolute value that you correct in the "use absolute value" commit isn't a bug. https://github.com/linux-surface/iptsd/issues/38#issuecomment-850820715

**Comment by StollD** [comment]
@mklss Would there be any side effects if we reverted the first commit? (https://github.com/linux-surface/iptsd/pull/39/commits/d1c4df95401989abaefeaffa12784c4d3a5b4d56). Given that you dont use the `dev1` and `dev2` variables later on, it should be fine?

**Pull request merged**
