### PR TITLE
[error] Failed to get IPTS device info from driver: No such process

### PR DESCRIPTION
**Pull request by typeriter**
@Xiashangning First, thank you for your work on this project.

I'm running a Surface Pro 7 i5 8gb 256gb version. Latest BigSurface and latest OpenCore. When I install the IPTSDaemon I get no error message, and the files are moved correctly. But when I reboot there's no touch support. When I try to run IPTSDaemon manually I get:

jeffrey@Jeffreys-MacBook-Pro ~ % /usr/local/bin/IPTSDaemon ; exit;
[08:45:10.881] [error] Failed to get IPTS device info from driver: No such process

Any help would be greatly appreciated.

[IOREG.txt](https://github.com/linux-surface/iptsd/files/10831740/IOREG.txt)

### CODE REVIEW

**Comment by qzed** [comment]
You probably want to ask this at https://github.com/Xiashangning/IPTSDaemon instead.

We don't officially support macOS and most likely never will. Without knowing much about kernel development on Macs, I'm going to go ahead and guess that the whole kernel to daemon API is quite different. And the error message you report seems to indicate that it's an issue with that. Also, the error message doesn't exist in our sources.

**Comment by StollD** [comment]
> Also, I'm not sure why you opened this as a PR.

Because the other repo has issues disabled, and pressing the "New pull request" button defaults to opening a pull request to this repository.

@Xiashangning You might want to consider enabling the issue tracker on your fork.

**Comment by typeriter** [comment]
@qzed and @StollD, I apologize for this post ending up here. Tagging @Xiashangning as well.

**Comment by Xiashangning** [comment]
WTF is this... Truly sorry for this mess

> We don't officially support macOS and most likely never will. Without knowing much about kernel development on Macs, I'm going to go ahead and guess that the whole kernel to daemon API is quite different. And the error message you report seems to indicate that it's an issue with that. Also, the error message doesn't exist in our sources.

Yeah, the whole thing is that I have ported your great work to macOS so that hackintosh users of Surface devices could experience touch screen on macOS even the real MacBook users can't :P

So I've change a lot the code. This error is completely from my code's side not yours.

> You might want to consider enabling the issue tracker on your fork

You are right. I don't know why it is not enabled in the first place... and I forgot to check that. Now my fork has issue tracker and we will solve it there.

Again, sorry for this incident. @typeriter we will discuss this on my fork instead.

**Comment by qzed** [comment]
> You are right. I don't know why it is not enabled in the first place... and I forgot to check that. Now my fork has issue tracker and we will solve it there.

It's disabled by default for any forks. No worries, no harm done, I was just a bit confused.

**Pull request closed without merging**
